language: python
python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev --deploy --system --ignore-pipfile

script:
  - black --check .
  - python -m pytest
  - pylint -f parseable --errors-only --rcfile setup.cfg env_manager tests
  - mypy --strict .
